STANDARD_WINDOW_WIDTH = 900
STANDARD_WINDOW_HEIGHT = 600
STANDARD_WINDOW_SIZE = f'{STANDARD_WINDOW_WIDTH}x{STANDARD_WINDOW_HEIGHT}' #widthxheight
STANDARD_TEXT_BOX_WIDTH = 450
STANDARD_TEXT_BOX_HEIGHT = 100
TREATMENT_DESCRIPTION_CHARACTER_LIMIT = 400



#window name constant
WINDOW_LANDING = "LandingWindow"
WINDOW_CUSTOMER_DETAIL = "CustomerDetailWindow"
WINDOW_CONDITION_DETAIL = "ConditionDetailWindow"
WINDOW_TREATMENT_DETAIL = "TreatmentDetailWindow"
WINDOW_ADD_TREATMENT = "AddTreatmentWindow"
WINDOW_EDIT_TREATMENT = "EditTreatmentWindow"
WINDOW_EDIT_CONDITION = "EditConditionWindow"
WINDOW_ADD_CUSTOMER = "AddCustomerWindow"