STANDARD_WINDOW_WIDTH = 900
STANDARD_WINDOW_HEIGHT = 600
STANDARD_WINDOW_SIZE = f'{STANDARD_WINDOW_WIDTH}x{STANDARD_WINDOW_HEIGHT}' #widthxheight
STANDARD_TEXT_BOX_WIDTH = 500
TREATMENT_DESCRIPTION_CHARACTER_LIMIT = 400
